function [TEdelay, TRdelay, minTE, minTR] = calc_te_tr_delays( ...
    rf, rfsat, gzSS, gzSSR, gxPre, gyPre, gzPre, gro, ...
    gxSpoil, gySpoil, gzSpoil, ETL, TE, TR, sys)
%% calc_te_tr_delays  Compute TE and TR padding delays for an EPI sequence.
%   Inputs are Pulseq gradient/RF objects and scalar timing parameters.
%   Returns TEdelay and TRdelay (both rounded to blockDurationRaster).
%   Issues a warning (does not error) if the prescribed TE/TR is unachievable.

minTE = 0.5*mr.calcDuration(rf) ...
      + mr.calcDuration(gzSSR) ...
      + max([mr.calcDuration(gxPre), mr.calcDuration(gyPre), mr.calcDuration(gzPre)]) ...
      + (ETL/2 - 0.5) * mr.calcDuration(gro);

if TE >= minTE
    TEdelay = floor((TE - minTE)/sys.blockDurationRaster) * sys.blockDurationRaster;
else
    warning('Minimum achievable TE (%.3f ms) exceeds prescribed TE (%.3f ms).', ...
            minTE*1e3, TE*1e3);
    TEdelay = 0;
end

minTR = mr.calcDuration(rfsat) ...
      + max([mr.calcDuration(gxSpoil), mr.calcDuration(gzSpoil)]) ...
      + max([mr.calcDuration(rf), mr.calcDuration(gzSS)]) ...
      + mr.calcDuration(gzSSR) ...
      + TEdelay ...
      + max([mr.calcDuration(gxPre), mr.calcDuration(gyPre), mr.calcDuration(gzPre)]) ...
      + ETL * mr.calcDuration(gro) ...
      + max([mr.calcDuration(gxSpoil), mr.calcDuration(gySpoil), mr.calcDuration(gzSpoil)]);

if TR >= minTR
    TRdelay = floor((TR - minTR)/sys.blockDurationRaster) * sys.blockDurationRaster;
else
    warning('Minimum achievable TR (%.3f ms) exceeds prescribed TR (%.3f ms).', ...
            minTR*1e3, TR*1e3);
    TRdelay = 0;
end
end
